//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoKarting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int PasswordId { get; set; }
        public int UserId { get; set; }
        public int Password1 { get; set; }
        public int Salt { get; set; }
    
        public virtual User User { get; set; }
    }
}
