//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoKarting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Customers = new HashSet<Customer>();
            this.Logins = new HashSet<Login>();
            this.Passwords = new HashSet<Password>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<Password> Passwords { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
